---

image: elixir:1.6

variables:
  MIX_ENV: test

test:
  stage: test
  script:
    - mix local.hex --force
    - mix deps.get
    - mix credo
    - mix test --exclude not_implemented
  cache:
    paths:
      - deps/
