---

image: elixir:1.6-otp-21

variables:
  MIX_ENV: test

test:
  stage: test
  script:
    - mix local.hex --force
    - mix local.rebar --force
    - mix deps.get
    - mix deps.compile
    - mix do compile --warnings-as-errors
    - mix credo
    - mix coveralls --exclude not_implemented
  cache:
    paths:
      - deps/
